### PR TITLE
Splitting up test files into tests/routes.test.js and tests/general.test.js

### PR DESCRIPTION
**Pull request by Anirudhkarnam**
## PR Type
*This pull request is a/deals with...*
- [ ] Fix (Bug/Security/Otherwise)
- [ ] Optimization
- [ ] Documentation Update
- [ ] Enhancement/Feature Addition
- [x] Other

## PR Category
*This pull request modifies at least one of the following...*
- [ ] Server Backend (`/src/`)
- [ ] Curriculum Files (`/static/curriculum/`)
- [ ] Website Front End (`/views/`, `/static/css/`, `/static/js/`)
- [ ] Editor (`/views/editor.ejs`, `/static/js/editor.js`)
- [ ] Other Static Files (`/static/`)
- [ ] Organization/Dependencies/Quality of Life/Other

## Misc.
*By creating this pull request you agree to the following...*
- [ ] I have read the [Ideoxan Repository Code of Conduct](https://github.com/ideoxan/ideoxan/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have read the [Ideoxan Repository Contributing Guidelines](https://github.com/ideoxan/ideoxan/blob/master/CONTRIBUTING.md)
- [ ] I read and agree to the [Terms and Conditions](https://ideoxan.com/tos) and [Privacy Policy](https://ideoxan.com/privacy) of Ideoxan

### CODE REVIEW

**Review by Skyclo — APPROVED** [review]
Works beautifully! Thank you for your contribution!

**Comment by Anirudhkarnam** [comment]
@Skcylo

Thank you for the opportunity. Can you add the tag as hacktoberfest-accepted. 

Thanks

**Comment by Skyclo** [comment]
> @Skcylo
> 
> Thank you for the opportunity. Can you add the tag as hacktoberfest-accepted. 
> 
> Thanks 

The repo is already labeled with the Hacktoberfest tag and therefore will count towards your required PRs.

**Comment by Anirudhkarnam** [comment]
> > @Skcylo
> > Thank you for the opportunity. Can you add the tag as hacktoberfest-accepted.
> > Thanks
> 
> The repo is already labeled with the Hacktoberfest tag and therefore will count towards your required PRs.

Sure. Thanks

**Pull request merged**
