### PR TITLE
Updated README.md with logo

### PR DESCRIPTION
**Pull request by micahlt**
This updates the README to be a little more descriptive and adds a logo.

### CODE REVIEW

**Comment by locness3** [comment]
you should add an alt text to the image

**Comment by micahlt** [comment]
Eh, but the logo is just to enhance.  The title of the website is right
below it.  Is alt text really necessary?

**Comment by locness3** [comment]
I think just "logo" can be enough

**Comment by micahlt** [comment]
alright, then.
<https://dribbble.com/micahlt> <https://github.com/micahlt>
<https://dribbble.com/micahlt>

*Micah Lindley*

Web Developer | Graphic Designer | Musician

*(731) 903-7085 <(731)+903-7085>*

*micahincorporated@gmail.com <micahincorporated@gmail.com>*

*www.micahlindley.com <http://www.micahlindley.com>*

**Comment by locness3** [comment]
Congrats mate, you just leaked your phone number

**Comment by micahlt** [comment]
Got you, that's a web-based number xD

**Comment by locness3** [comment]
hmm

**Comment by micahlt** [comment]
@locness3 Okay, added alt text.

**Pull request merged**
