### PR TITLE
Deploy time CSS optimization

### PR DESCRIPTION
**Pull request by ArduinoidIOT**
I added a new 'css_optimizer.js' that minifies the css at runtime
NOTE: this requires the OPTIMIZE environment variable to be set.
Also, don't use this in development (you won't be able to read it anymore)

### CODE REVIEW

**Comment by ArduinoidIOT** [comment]
Also, this is my first ever node.js program

**Comment by Skyclo** [comment]
I wanted to let you know that you aren't properly authenticated on your git CLI. This means that all of your commits have not been tied to your account. If you would like for me to go back and tie it to your Github account (so it also displays on the website) please let me know.

**Comment by ArduinoidIOT** [comment]
No, it's fine. I'm too lazy to add a gpg key.

**Comment by ArduinoidIOT** [comment]
Also, there's gonna be a buildpack version of this

**Comment by Skyclo** [comment]
Don't worry about the GPG key. I can easily set the commit author to you quickly. I think you should at least be included on the website due to the amount of work you have put in.

**Comment by ArduinoidIOT** [comment]
Okay, sure.

**Comment by Skyclo** [comment]
It seems like changing the author of commits is harder than I thought 🤔 ...

What you can do from now to get credit for your contribution is by running the two commands below and replacing them with the proper information.
```bash
git config --global user.name <your username>
git config --global user.email <your email>
```
I will review the PR tomorrow

**Comment by ArduinoidIOT** [comment]
There, I set it to my github username. Is that all right?

**Comment by ArduinoidIOT** [comment]
I use JavaScript (DOM) so I think I had an edge there

**Pull request merged**
