### PR TITLE
add default config file

### LINKED ISSUE #75: Default Config File
**Is your feature request related to a problem? Please describe.**
It is bad practice not to have a default config file. Also, secrets can not be stored in its current state. 

**Describe the solution you'd like**
Make the current configuration file a default one (ie. change to `config.default.json`) and have that as a fall back if there is no `config.json` available. Also blacklist `config.json` but not `config.default.json` in `.gitignore` so that secrets can be placed in the config file. This will reduce dependency on the environment variables and make customization easier.

**Describe alternatives you've considered**
Environment variables are out of the question at this point and a transition to a blacklisted config file would be easier to read and edit.

### PR DESCRIPTION
**Pull request by fuzzmz**
## Description
Add default config file to fall back to in case custom config file is not found.

## Related Issues and Files
Fixes #75 

## PR Type
*This pull request is a/deals with...*
- [ ] Fix (Bug/Security/Otherwise)
- [ ] Optimization
- [ ] Documentation Update
- [x] Enhancement/Feature Addition
- [ ] Other

## PR Category
*This pull request modifies at least one of the following...*
- [x] Server Backend (`/src/`)
- [ ] Curriculum Files (`/static/curriculum/`)
- [ ] Website Front End (`/views/`, `/static/css/`, `/static/js/`)
- [ ] Editor (`/views/editor.ejs`, `/static/js/editor.js`)
- [ ] Other Static Files (`/static/`)
- [x] Organization/Dependencies/Quality of Life/Other

## Misc.
*By creating this pull request you agree to the following...*
- [x] I have read the [Ideoxan Repository Code of Conduct](https://github.com/ideoxan/ideoxan/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [Ideoxan Repository Contributing Guidelines](https://github.com/ideoxan/ideoxan/blob/master/CONTRIBUTING.md)
- [x] I read and agree to the [Terms and Conditions](https://ideoxan.com/tos) and [Privacy Policy](https://ideoxan.com/privacy) of Ideoxan

### CODE REVIEW

**Comment by Skyclo** [comment]
Thank you @fuzzmz for your contribution! If you could comment under the related issue (#75) and request to have the issue assigned to you, that would be great!

**Comment by fuzzmz** [comment]
@Skyclo, not sure if you prefer the try catch way or adding an external dependency which can handle the fallback ([config.json](https://www.npmjs.com/package/config.json)). I'm leaning more towards not adding extra deps for such a small thing, but it's up to you.

**Comment by Skyclo** [comment]
> @Skyclo, not sure if you prefer the try catch way or adding an external dependency which can handle the fallback ([config.json](https://www.npmjs.com/package/config.json)). I'm leaning more towards not adding extra deps for such a small thing, but it's up to you.

I took a brief look at the code and I think using a try/catch method will work just fine. We already have a lot of dependencies as it is and streamlining it is probably best. However, that being said, if you believe that the config.json package will be a lot easier to use in the long run, then use it. I will still have to review later today when I can get access to a computer that can test and run the PR.

**Comment by fuzzmz** [comment]
I honestly think that for this use-case relying on an external dependency just doesn't make sense, so I'll stick to try/catch. Consider this ready for review in this case.

**Review by Skyclo — APPROVED** [review]
Tested it and it works wonderfully! Thank you for contributing to Ideoxan!

**Pull request merged**
